$folder = "\\192.168.0.0\data\Departments\IT\Fortinet_Daily_Backup" 

$date = Get-Date -Format "dd-MM-yyyy"

$todayFile = Get-ChildItem $folder -Filter "*$date*.conf" -ErrorAction SilentlyContinue | Select-Object -First 1

$smtpServer = "smtp.office365.com"
$port = "587"

$username = "SENDING PERSON EMAIL ID"
$password = "YOUR PASSWORD"

$securePassword = ConvertTo-SecureString $password -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential ($username,$securePassword)

$mail = New-Object System.Net.Mail.MailMessage
$mail.From = $username
$mail.IsBodyHtml = $true

if ($todayFile) {

$mail.To.Add("EMAIL RECIVERS EMAIL ID ")
$mail.CC.Add("RECIVERS EMAIL ID ")

$mail.Subject = "Fortinet Daily Configuration Backup | $date"

$body = @"
Hello,<br><br>

Please find attached the Fortinet 100F daily configuration backup for <b>$date</b>.<br><br>

<b>Backup File:</b> $($todayFile.Name)<br><br>

<hr>

Thanks & Regards,<br>
SENDING PERSON NAME<br>
SENDING PERSON ROLE<br>
Mobile: CONTACT NUMBER<br>
Email: SENDING PERSON EMAIL ID <br>
Site: COMPANY WEBSITE<br><br>

<small>
This is an automated email generated by the IT system for the daily Fortinet firewall backup.
</small>
"@

$mail.Body = $body
$mail.Attachments.Add($todayFile.FullName)

}

else {

$mail.To.Add("PERSON DETAIL WHO WANT TO NOTIFIED IF BACKUP GOT FAILED")
$mail.CC.Add("CC")

$mail.Subject = "ALERT: Fortinet Backup Missing | $date"

$body = @"
Hello,<br><br>

The Fortinet backup for <b>$date</b> was not found in the backup directory.<br><br>

Please check the firewall backup process immediately.<br><br>

Backup Location:<br>
LOCATION WHERE BACKUP IS LOCATED \\SERVERIP\PATH\FILE<br><br>

<hr>

This is an automated alert generated by the IT monitoring system.
"@

$mail.Body = $body

}

$smtp = New-Object Net.Mail.SmtpClient($smtpServer,$port)
$smtp.EnableSsl = $true
$smtp.Credentials = $cred

$smtp.Send($mail)
